// Supabase database types
// Generated by Supabase CLI or manually defined

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          password_hash: string;
          name: string;
          role: "admin" | "investor" | "immortal";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          password_hash: string;
          name: string;
          role: "admin" | "investor" | "immortal";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          password_hash?: string;
          name?: string;
          role?: "admin" | "investor" | "immortal";
          created_at?: string;
          updated_at?: string;
        };
      };
      investor_applications: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          name: string;
          phone: string | null;
          entity_type: "individual" | "trust" | "llc" | "corporation";
          verification_method:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          verification_status:
            | "pending"
            | "under_review"
            | "approved"
            | "rejected";
          nda_signed: boolean;
          nda_signature: string | null;
          nda_signed_at: string | null;
          investment_amount: number | null;
          payment_status: "pending" | "processing" | "completed" | "failed";
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email: string;
          name: string;
          phone?: string | null;
          entity_type: "individual" | "trust" | "llc" | "corporation";
          verification_method?:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          verification_status?:
            | "pending"
            | "under_review"
            | "approved"
            | "rejected";
          nda_signed?: boolean;
          nda_signature?: string | null;
          nda_signed_at?: string | null;
          investment_amount?: number | null;
          payment_status?: "pending" | "processing" | "completed" | "failed";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string;
          name?: string;
          phone?: string | null;
          entity_type?: "individual" | "trust" | "llc" | "corporation";
          verification_method?:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          verification_status?:
            | "pending"
            | "under_review"
            | "approved"
            | "rejected";
          nda_signed?: boolean;
          nda_signature?: string | null;
          nda_signed_at?: string | null;
          investment_amount?: number | null;
          payment_status?: "pending" | "processing" | "completed" | "failed";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      investor_documents: {
        Row: {
          id: string;
          application_id: string;
          document_type: string;
          file_name: string;
          file_url: string;
          status: "pending" | "verified" | "rejected";
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          document_type: string;
          file_name: string;
          file_url: string;
          status?: "pending" | "verified" | "rejected";
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          document_type?: string;
          file_name?: string;
          file_url?: string;
          status?: "pending" | "verified" | "rejected";
          uploaded_at?: string;
        };
      };
      investors: {
        Row: {
          id: string;
          user_id: string;
          application_id: string;
          shares: number;
          share_price: number;
          investment_amount: number;
          ownership_percentage: number | null;
          verification_date: string | null;
          verification_method:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          application_id: string;
          shares: number;
          share_price: number;
          investment_amount: number;
          ownership_percentage?: number | null;
          verification_date?: string | null;
          verification_method?:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          application_id?: string;
          shares?: number;
          share_price?: number;
          investment_amount?: number;
          ownership_percentage?: number | null;
          verification_date?: string | null;
          verification_method?:
            | "document_upload"
            | "third_party"
            | "professional_letter"
            | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
